version: '2'
services:
  h2:
    image: 'oscarfonts/h2:2.1.210'
    container_name: 'java-h2'
    environment:
      - 'H2_USER=sa'
      - 'H2_PASSWORD=password'
      - 'H2_DB=v4eDB'
  #      - 'H2_HOST_AUTH_METHOD=trust'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080